### ISSUE TITLE
Adding chroot mode

### ISSUE THREAD

**Issue by ZhymabekRoman** [ptitSeb/box86#242]
Hello there! I would really like to run the x86 system in a chroot container using box86. I think it will be much easier to work in the system than it is now, and many people support my idea. I've been working for a month and I can't run anything on box86, except my Hello World program, because all my boring programs require x86 dependencies, those that are not suitable in armhf. I understand that you didn't go down this path because you wanted to achieve speed. But for the sake of speed, you sacrifice convenience. For example, in Exagear, I was able to install and run all these programs in just a few seconds, because you are already working inside x86, and you are already thinking through your steps. It's a pity of course the Exagear project, died out of the blue, now by the way it is being developed by Huawei. And I think it will also be easier for you to develop, you will not need to write a wrapper for each library, there are too many distributions, and the library too, you can't fix all the bugs, you will always have to fix bugs when the new system is released. Vaughn Exagear for example still works great. 

I don't really understand how it all works technically, but it seems That exagear chroot containerization works on the basis of gdb. I think in box86, a chroot container without root can be implemented based on ptrace-proot.

Thank you so much for box86!
Sorry for my English)

**Comment by ptitSeb** [comment]
Hi,

There no special limitation in running box86 in a chroot.

And box86 is design to be as simple as possible: in fact, you don't need any chroot to run box86, and it can launch program just by itself. How can it be more simple?

Now, youneed to understand that how box86 is designed differt a lot from Exagear/Qemu phylosophy. Box86 works by wrapping system libs. That's why it doesn't need a full chroot to run. Instead of needing an x86 copy of libc.so, it will use your armhf copy of libc.so. It will do the same for all system libs (like ld-linux, libm, libphtread, etc.), but also some higher level libs, like SDL, pulseaudio, OpenGL and other.
What is not wrapped is C++ library. So you still need a copy of libstdc++.so for example.

What doesn't work on box86 (because of that) are statically linked program.

I don't know what doesn't work on your side, so I cannot help you.

And again, box86 can use a chroot, but it's not designed for that. And it's not a replacement for Exagear/Qemu, it' something different.

**Comment by ZhymabekRoman** [comment]
Ok. Thanks
