### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by yiskwang** [ptitSeb/box86#254]
I thought Box86 as a variant of WINE, and I just installed it on raspberry PI 3.
Now, how can I execute an .exe file?

Can I execute an executable on terminal like #box86 sample.exe ?

**Comment by ptitSeb** [comment]
box86 is not wine. Box86 allow you tu run x86 linux executable on ARM. But you can run x86 wine with box86... For this kind of help, I suggest you visit the Discord channel listed in the Readme. This is not something to be handled in a bug ticket.

**Comment by WheezyE** [comment]
[TwisterOS](https://twisteros.com/download.html) makes Box86 very easy to use.

If you really really want to install and use Box86 on vanilla/stock Raspberry Pi OS, there are some [Raspberry Pi OS install instructions on the Discord](https://discord.com/channels/670543161525010442/700827603623346278/758440669600940072), but I would recommend TwisterOS instead, since this is more of an advanced method for using Box86 and doesn't include instructions for how to install or configure mesa or any other scripts or things that are useful when running Box86.

In Twister OS, just go to the terminal and run the program you want to run and box86 should pop up automatically, I believe (if running wine, just type `wine`, for example, and box86 will run automatically via some binfmt magic)

Would anybody mind if I closed this bug ticket?

**Comment by ptitSeb** [comment]
Wait until tomorow if no response, and then yeah, I think it can be clased after that.

**Comment by WheezyE** [comment]
> I just installed it raspberry PI 3.

I don't have much experience with this split kernel stuff, but I found some steps for compiling a 3G/1G kernel for the RPi3 [here](https://www.novaspirit.com/2019/04/15/run-x86-arm/) from NovaSpirit:

> 
> Follow this guide from official raspberry pi to compile your raspberry pi kernel. (if you are not using raspberry pi, you will need to find the steps to compiling and installing there kernel)
> 
> https://www.raspberrypi.org/documentation/linux/kernel/building.md
> 
> you will need to modify the .config after the
> `make bcm2709_defconfig`
> by commenting out the
> `# VMSPLIT_2G=y`
> and remove the comment block from
> `# VMSPLIT_3G=y`
> there might be some cases (ie tinkerboard) where you will need to enable binfmt_misc so check for that as well in the .config

I've head that the Pi4 has a 3G/1G kernel by default, which I think is why you don't have to do this step on Pi4.

**Comment by ptitSeb** [comment]
Yes, exactly. Maybe I should add a mention on the README in the Wine section?

**Comment by WheezyE** [comment]
That might not be a bad idea / it might be helpful for new users of box86, just as a heads-up that it won't work on Pi3 right away until they do some extra steps with the Pi3 kernel

**Comment by yiskwang** [comment]
Thank  you very much.

**Comment by WheezyE** [comment]
Yeah, man. I hope that helped a bit.

@ptitSeb lol look like I can't actually close this ticket (I think because I haven't contributed code to the git), but I think it's resolved
