### ISSUE TITLE
Getting your wine for box86

### ISSUE THREAD

**Issue by nru1979** [ptitSeb/box86#263]
I see here and there people having trouble installing portable x86 wine on their pi.
Of course, as a starter you can use the one found on twisteros homepage.
If you want more, playonlinux hosts alot of versions there:

https://www.playonlinux.com/wine/binaries/linux-x86/

Download .pol file, use bzip2 to uncompress.
I personally use 3.20.

So far I have not found any portable wine on winehq, and plain unpacking winehq packages does not work.
If someone has a solution to run box86 with newer than 3.20 version of wine, I am preneur.

**Comment by ptitSeb** [comment]
I used many different version of wine without issue. I use the 5.22 from PlayOnLinux. I use the building service packages, from there: https://www.playonlinux.com/wine/binaries/phoenicis/upstream-linux-x86/

Note that stagging package rarely works, at least not the latest on (like 5.10+).

**Comment by AxlPr** [comment]
I cobbled together a version by downloading the debian packages from WineHq here:
https://dl.winehq.org/wine-builds/debian/dists/buster/main/binary-i386/
For example I downloaded:
wine-stable_5.0.3_buster_i386.deb
wine-stable-i386_5.0.3_buster_i386.deb
Then for both I extracted the data.tar files using 7-Zip on a PC. Next I then copied these onto my Pi and extracted the files under \opt\wine-stable\ into folder structure similar to the Twister OS version.
It's a bit Heath Robinson but does the job and seems to work ok. I did notice that when switching between difference version of wine you may have to delete the .wine directory it creates otherwise you can get errors starting the programs.

**Comment by ptitSeb** [comment]
I'll close this ticket soon, unless someone as a good reason to keep it open.

**Comment by WheezyE** [comment]
I think with the i386-wine instructions page in the readme now, we can probably close this ticket?
