### ISSUE TITLE
x86_64 build supported?

### ISSUE THREAD

**Issue by voltagex** [ptitSeb/box86#50]
For testing purposes it'd be easier to run this on an x86_64 desktop. 
At the moment the build errors out with the following.

[error.log](https://github.com/ptitSeb/box86/files/3613393/error.log)

**Comment by ptitSeb** [comment]
For now, native x86_64 build is not supported. But x86 is, so you need 32bits libs. Look in COMPILE.md for the compile switch to activate to get a working build.

**Comment by madscientist159** [comment]
What would be required to get 64-bit builds working?  I have a system that is 64-bit *non-x86*, no 32-bit compatibility available.  Goal is running old x86 (32-bit) games.

**Comment by ptitSeb** [comment]
It's a lot of work.

For an 64bits build, taking asside the dynarec that would need a new backend (i.e. a rewrite), there are a lot of case to check in the code to differenciante "emulated" `void*` (32bits) and "native" `void*` (64bits).
The main issue would be memory allocation in the wrappers. The idea of box86 is to directly map x86 function call with native function. So, for a function like `malloc(...)`, some mecanism needs to be pt in place to be sure the returned pointer is 32bits compatible. Either by using some custom function, or by creating a map (that's the Hangout approach I think). The custom function is nice because you directly have a compatible pointer, but you need to have a custom funciton for every function that allocate memory (and there are a lot, and and it's not limited to `libc`). The second approach means you need to use the map for every function that use a pointer (so you get a speed hit because of the map, and you always have the risk of missing some pointer in a structure...). Maybe something intermediary could be done (some mmap or similar mecanism to mirror the memory?), but I haven't done much research on that.

I think a box86_64, targetting x86_64 would be a bit simpler, but because of the complexity of the x86_64 architecture, still a large amount of work.
