### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by xylo04** [ptitSeb/box86#561]
# Setup

I installed a fresh copy of Raspberry Pi OS 11/Bullseye dated from October 2021, then replaced the default `pi` user with a different account (as a minor security improvement). After that, I followed the instructions for installing box86 via the
[Twister tgz instructions](https://github.com/ptitSeb/box86/blob/f27361b/docs/X86WINE.md#installing-wine-for-box86-on-raspberry-pi-os-from-twister-os-faq-tgz-files) verbatim.

# Expected

When I run `wine wineboot` at the end of the installation, I should see that the `~/.wine` prefix directory was created

# Actual

```
chris@winlinkpi:~ $ wine wineboot
/home/chris/wine/bin/wine: 1: Syntax error: "(" unexpected
```

# Conjecture

I have another Raspberry Pi running RPi OS 10/Buster, and do not see the same issue. Maybe the tar distributable is not compatible with Bullseye? I'll try compiling from source and see if I can confirm.

**Comment by xylo04** [comment]
Please ignore me. :sweat_smile: I was supposed to compile box86 anyway but forgot that step. The `Syntax error` I'm seeing is probably still valid but related to wine, not box86.

**Comment by WheezyE** [comment]
Don't feel bad - the install is tricky since it's all i386 on ARM.  I just wanted to say that I updated my Pi to bullseye today and had some weird wine errors too with wine-devel-5.19-buster and wine-devel-5.19-bullseye.  I forgot to write the errors down exactly, but wine just refused to run winecfg, boot, or run programs.  I change wine from 5.19 to 6.19 and wine behaved normally again.  I'm updating my Winelink script accordingly with the changes pretty soon!
