### ISSUE TITLE
Segmentation Fault on Raspbian

### ISSUE THREAD

**Issue by CalcProgrammer1** [ptitSeb/box86#6]
I built the project according to the compiling guide for other ARM machine.  It built successfully.  Running the resulting binary always seems to result in a segmentation fault.  I was going to try running the Steam binary with it but even running with no input gives a segmentation fault.  I tried BOX86_LOG=2 and got no additional messages before segfault.

I'm running Raspbian on a Raspberry Pi 3 model B.

I also tried to build using aarch64 Gentoo also on the Pi 3 but there were build errors.

**Comment by ptitSeb** [comment]
Are you building on a 64bits system? You need to build it as a 32bits binary then (using `-m32`), 64bits build will not work.
If it's a 32bits build, can you do a gdb backtrace?

**Comment by ptitSeb** [comment]
One other thing you can try is guess another value for https://github.com/ptitSeb/box86/blob/master/CMakeLists.txt#L133

Instead of `0xA8000000` try lower or higher values, like `0x90000000` or `0xC0000000` and see if it improve things.
Try `ctest` first

**Comment by danieloneill** [comment]
./box86 won't start, same issue. segfault. I've tried with 0xC0000000 and 0x90000000
Raspbian Jessie, GCC 4.9.2
Raspi 3

I don't even know where to start debugging this. gdb doesn't help:

```
(gdb) run
Starting program: /home/doneill/box86/build/box86 
During startup program terminated with signal SIGSEGV, Segmentation fault.
(gdb) bt
No stack.
(gdb) 
```

Any other suggestions?

**Comment by ptitSeb** [comment]
Well, remove the whole line then, just to be sure (and you are sure it's a 32bits build?).

(Also, you can maybe debug the initialisation using `starti` then `c` instead of `run`)

**Comment by danieloneill** [comment]
Dude my pi can't make 64bit.

I'm sure.


I even added -m32 and the compiler complained and died.

**Comment by ptitSeb** [comment]
Then it's probably that line 133 of CMakeList.txt, to force the program to load at a certain address, that the linker doesn't like.

So either remove the line (but the risk is that some x86 program will not able to load because the address range will be occupied by box86 itself), or maybe try to use `gold` instead of `ld` (use `-fuse-ld=gold -fuse-linker-plugin` in flags)

**Comment by CalcProgrammer1** [comment]
I removed the line with the address and rebuilt box86.  It works now, no segfault when running the binary.  I got it to run the binary installer for SPAZ (from Humble Bundle).  Going to try some more games now.

**Comment by Askmewho** [comment]
yeah, Ive tried your flags @ptitSeb , but they didn't fix the issue, only deleting that line.

**Comment by ptitSeb** [comment]
And without that line you both @CalcProgrammer1 and @Askmewho can launch what you want? whitout having a "Cannot create memory map (@somes address) for elf" message?

**Comment by Askmewho** [comment]
the only interesting "game" Ive tried its mugen (linux x86 binary) and I couldnt use it.

pi@pi:~/Desktop/mugen $ BOX86_PATH=/home/pi/Desktop/mugen box86 mugen
Using default BOX86_LD_LIBRARY_PATH: ./:lib/
BOX86_PATH: /home/pi/Desktop/mugen/
Counted 60 Env var
Looking for mugen
Section Header Entry size incorrect (0 != 40)
Error: reading elf header of /home/pi/Desktop/mugen/mugen

**Comment by Askmewho** [comment]
I get the following trying to execute both setup and binary of HMM3 (linux)

pi@pi:~/Desktop/HeroesOfMightAndMagic3/setup.data/bin/x86 $ BOX86_PATH=/home/pi/Desktop/HeroesOfMightAndMagic3/setup.data/bin/x86 box86 setup 
Using default BOX86_LD_LIBRARY_PATH: ./:lib/
BOX86_PATH: /home/pi/Desktop/HeroesOfMightAndMagic3/setup.data/bin/x86/
Counted 60 Env var
Looking for setup
Error: Unsupported Syscall 0x88h (136)

pi@pi:~/Desktop/HeroesOfMightAndMagic3/setup.data/bin/x86 $ BOX86_PATH=/home/pi/Desktop/HeroesOfMightAndMagic3/bin/x86 box86 heroes3
Using default BOX86_LD_LIBRARY_PATH: ./:lib/
BOX86_PATH: /home/pi/Desktop/HeroesOfMightAndMagic3/bin/x86/
Counted 60 Env var
Looking for heroes3
Error: Unsupported Syscall 0x88h (136)

not related whit memory map, obviously
i will try another one next days. thanks

**Comment by ptitSeb** [comment]
I need to add support for syscall 136: sys_personality
I'll do that, seems easy.

**Comment by Askmewho** [comment]
Good!!

**Comment by Askmewho** [comment]
now:
Error: Unsupported Syscall 0x31h (49)
:(

**Comment by Askmewho** [comment]
on stardew valley I get the following 
pi@pi:~/Desktop/stardew/data/noarch/game $ BOX86_PATH=/home/pi/Desktop/stardew/data/noarch/game box86 StardewValley.bin.x86
Using default BOX86_LD_LIBRARY_PATH: ./:lib/
BOX86_PATH: /home/pi/Desktop/stardew/data/noarch/game/
Counted 61 Env var
Looking for StardewValley.bin.x86
Using native(wrapped) libm.so.6
Using native(wrapped) librt.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Error: Symbol getresuid not found, cannot apply R_386_JMP_SLOT @0x83cb0e0 (0x80568f6)
Error: Symbol getprotobyname not found, cannot apply R_386_JMP_SLOT @0x83cb128 (0x8056a16)
Error: Symbol madvise not found, cannot apply R_386_JMP_SLOT @0x83cb16c (0x8056b26)
Error: Symbol cabs not found, cannot apply R_386_JMP_SLOT @0x83cb294 (0x8056fc6)
Error: Symbol sigdelset not found, cannot apply R_386_JMP_SLOT @0x83cb2a0 (0x8056ff6)
Error: Symbol mincore not found, cannot apply R_386_JMP_SLOT @0x83cb2f8 (0x8057156)
Error: Symbol __fgets_chk not found, cannot apply R_386_JMP_SLOT @0x83cb430 (0x8057636)
Error: Symbol msync not found, cannot apply R_386_JMP_SLOT @0x83cb448 (0x8057696)
Error: Symbol __libc_current_sigrtmax not found, cannot apply R_386_JMP_SLOT @0x83cb44c (0x80576a6)
Error: Symbol sigsuspend not found, cannot apply R_386_JMP_SLOT @0x83cb460 (0x80576f6)
*** Error in `box86': malloc(): memory corruption: 0x00d87730 ***
Abortado

**Comment by ptitSeb** [comment]
I have just pushed the missing syscall.

About stardew valley, it use C#, and so will probably not work on box86 for now. But it is playable fullspeed already using this method: https://magazine.odroid.com/article/playing-modern-fna-games-on-the-odroid-platform/
On an Odroid Xu4 it works well, you should get good result on Raspbian too: https://youtu.be/VUoeHWuwlMU

**Comment by Askmewho** [comment]
good, I will avoid C# games next time. thats for the advice, the FNA project seems wonderful, there are very good games. Ive never heard that feature of C# (the non arch dependence). thats because I am not a soft designer like you haha. I will test you push on a moment.

**Comment by Askmewho** [comment]
Sorry, ptitseb, i will test it on these days. the information than you give me about mono and fna games just blows my mind. I need to ask you a little advice. hope than you doesn't get this as offensive if I do a bit of off topic here. 

the problem its than I need to set a proper mojoshader profile, because I cant set it to glsl ES. it uses glsl or glsl120 (depende if I compile glsl120 or not). take note than I am not utilising your wrapper because the pi doesnt need it... but the pi doesnt manage well normal glsl (many blacks textures) 

IGLDevice: OpenGLDevice
OpenGL Device: VC4 V3D 2.1
OpenGL Driver: 2.1 Mesa 19.1.0-devel (git-edc7deec42)
OpenGL Vendor: Broadcom
MojoShader Profile: glsl120
EXT_swap_control_tear unsupported. Fall back to standard VSync.
EXT_swap_control_tear unsupported. Fall back to standard VSync.
FakeMODex : loading FMOD
initializing c# fmod

hope you understand than I am really close and cant contact you on other way. thank you so much.

**Comment by ptitSeb** [comment]
I'm not offended, no problem.

Now, I don't know well mojoshader, but you can probably force, in the code, the use of glsl_ES. 
But are you sure you can use GLES shaders with a OpenGL 2.0 context?
If you are sure, in `mojoshader_opengl.c`, line 1354, try to change ` if (ctx->have_opengl_es)` with `if (1)`. That should force the context. But again, your driver needs to accept GLES shader in GL context.
Another thing you can try also is, using `ccmake` to disable glsl120, so it fallback to glsl 1.10, that maybe will work better?

(it seems to me that maybe you "need" my wrapper after all :p )

**Comment by ptitSeb** [comment]
Also, I just thought of something. Maybe it's not a shader issue: as you seem to be trying StardewValley, I know this game use some quite large texture atlas.
Those Atlas have 2 "problem" that can make black texture on your side: 
1. They are not power of two
2. They are larger then 2048 pixel in one dimension.

I don't know well enough RPi, but maybe one (or both) can be an issue. Use glxinfo to have more detail, and check what is the maximum texture size, and if NPOT texture are supported.

With gl4es, NPOT texture are handled (and some workaround done if the hardware doesn't support NPOT, because GLES2 support for NPOT texture is limited by default), and for hardware that have limited texture size (like the Pandora, with 2048x2048 max), I use `LIBGL_SHRINK=11` environment variable to shrink large texture on the fly...
But if any of the two is an issu for the RPi Mesa driver, you will need to fallback to gl4es...

**Comment by Askmewho** [comment]
good! ive tested glsles on my gl envirionment and it works... but didnt solve my issue. I dont think its related to the kind of textures bastion has.Ii will try that variable too! but first...lets back and test your gl4es! Ive always avoid that because the clean way for me was mesa (and I update it too). this gl4es could support gles 3.x any time soon? because new arm boards has that profile... and panfrost could take some time. anyway, several news give us a lot of hope than panfrost will be ready soon enough. i hope to n2 reaches my country soon (there are a lot of import policies restrictions here) ..I am a bit tired of an 40 nm cpu as an arm development board.

**Comment by ptitSeb** [comment]
Bastion has even more texture than StardewValley.

gl4es will support GLES 3.x one day, it's on my TODO, but I have other things to do before that ("clean" support for TextureRectangle and Texture3D in shader, and some rework on how EGL/GLES lib are loaded and used, at least).

**Comment by Askmewho** [comment]
indeed,  but the problem i am experimenting with glsl had appeared on other projects too. I cant see the textures at all hahah. btw, I've tried your gl4es but it doesn't work without going to terminal (disable x interface), and even on that it send a lot of errors. I will continue that problem on your gl4es issue tracker after I check and try all possibilities so I could give you a decent report. going back to box86, i will retry on next days. 
![2019-04-10-181149_1920x1080_scrot](https://user-images.githubusercontent.com/39385643/55914280-23dad000-5bbd-11e9-8e00-12ddbc60b168.png)

**Comment by ToastyMod** [comment]
Old issue but my fork here https://github.com/ToastyMod/box86 has the cmake fix in it for convenience.

**Comment by ptitSeb** [comment]
I'll put this parameter behind a cmake option, that would be the easier I guess.
@ToastyMod : did you had some success in loading games or program?

**Comment by ToastyMod** [comment]
@ptitSeb I got rid of the segementation fault message and was able to load box86 but now I'm getting this (im trying to load a program called Carla):

pi@raspberrypi:~/Documents/Carla_2.0.0-linux32 $ ./START.sh
Using default BOX86_LD_LIBRARY_PATH: ./:lib/
Using default BOX86_PATH: ./:bin/
Counted 18 Env var
Looking for Carla
Error: Unsupported Syscall 0x7Ah (122)

**Comment by ToastyMod** [comment]
i guess i should add, this is the contents of START.sh:

export BOX86_PATH="/bin/"
export BOX86_LD_LIBRARY_PATH="/lib/"
sudo ./box86 Carla

**Comment by ptitSeb** [comment]
I'll add support for that syscall, that seems easy enough (unless there is some alignment issue, but I think it should be fine, it's just a bunch of strings)

**Comment by ToastyMod** [comment]
@ptitSeb sweet thanks!

**Comment by ptitSeb** [comment]
I guess I will close this issue, now that there is a "NOLOADADDR" parameter in the cmake, and thta should fix the initial issue.

**Comment by PKizzle** [comment]
I could compile and run box86 on Raspbian without any issue.

**Comment by ptitSeb** [comment]
Good. I'll close this issue then.
If there are some other issue mentioned here there are still, then a new ticket should be created.
