### ISSUE TITLE
Syntax Error rebuild_wrappers.py

### ISSUE THREAD

**Issue by MitchHS** [ptitSeb/box86#610]
Trying to cmake and receive the following error:

Generating ../src/wrapped/generated/functions_list.txt
  File "/home/xyz/box86/rebuild_wrappers.py", line 169
    __keys__: List[T]
            ^
SyntaxError: invalid syntax

**Comment by ptitSeb** [comment]
What's your python version?

**Comment by MitchHS** [comment]
> What's your python version?

3.5.3

**Comment by rajdakin** [comment]
Alright, I've tried to fix the issue, can you do the following commands:
```bash
git remote add rajdakin_side https://github.com/rajdakin/box86.git # This is to be able to cherry-pick
git fetch rajdakin_side
git cherry-pick dba95db133b8717ee8652442808285e90fc0a42e # This will get the fix attempt
make # Or `make PRINTER` if you only want to test the Python script

# And optionally:
git remote remove rajdakin_side # To remove my fork of box86 from your clone
```
and tell me if it worked?

**Comment by MitchHS** [comment]
It did, thank you @ptitSeb

**Comment by proxy-m** [comment]
@rajdakin  By unknown reason it does not work for Python 3.5.2 on same line. 
I have to revert to 10e849ce606309953ca7997fa6c2f7ee06c80cc4 commit (from 2020-11-17 12:03:35, when any python works fine).

Also it is strange for me, that you removed dba95db133b8717ee8652442808285e90fc0a42e old fix from branch on your repo.

**Comment by rajdakin** [comment]
This is strange... Are you sure you have the same issue? If not, please open a new issue instead of hijacking this one. Also, looking at the current file, it looks just like the fixed one. (Also, it definitely works with a more recent Python version, if you are able to install one.)
In any case, you should be able to ignore the error by replacing the `rebuild_wrappers.py` file by an empty file (which is not ideal, but would work, since the files generated are kept up-to-date in the repo).

The "old fix" as you say is still here, it has just been squashed with another one into c1c3674 which is part of the master branch (as can be seen in the linked PR #634 above).
