### ISSUE TITLE
Can I execute a native program from a x86 program

### ISSUE THREAD

**Issue by davidawesome02** [ptitSeb/box86#646]
I found [https://github.com/FEX-Emu/FEX](url) whitch is great btw, It runs like yours a x86 program in aarm processors, I have talked to someone about how it works, and with that one, they have a overlay file system, that to any x86 program looks like files that are on /path
but they are realy on /home/david/fex/path, this also allows you to call a x86 program, have that run a aarm program, and also have a x86 program call a x86 program, dose box86 do the same with overlayfs, and dose it allow calls back to aarm programs, (it seams yes, based off the website), and lastly dose this project have a discord server?

**Comment by ptitSeb** [comment]
Box86 doesn't have an overlay fs. It's a more simple approach than fex or qemu: box86 just run the program you want. Nothing else. It use armhf libs instead of x86 one for most system libs. And for the libs that it doesn't wrap, the x86 version needs to be provided. Box86 is provided with x86 version of libstdc++ and libgcc_s that are installed in `/usr/lib/i386-linux-gnu/` else libs in the current folder (or some variant are read).
Box86 is simpler to use. The only drawback of box86 is that it needs an armhf system (so a 32bits OS or armhf multiarch/chjroot) to run.
And yes, you can call back arm program from an x86 without problem.

As for discord, I'm on few server, you can find me there: https://discord.gg/FbXVSjbnqw

**Comment by ptitSeb** [comment]
Can this ticket be closed now?
