### ISSUE TITLE
wine32 run cef in box86,use opengl crash

### ISSUE THREAD

**Issue by 1322579329** [ptitSeb/box86#742]
When dynarec is enable, wine run cef use opengl crash in glTexImage2D,
disable dynarec will  work right. How to debug dynarec crash?
log：

49156.606:0158:trace:opengl:glTexImage2D (3553, 0, 32856, 4, 4, 0, 32993, 33639, (nil))
(nil): Stack is corrupted, aborting

==== CPU Registers ====
EAX=00000000 ECX=00000000 EDX=00000001 EBX=db440000 FLAGS=-CPA-S
ESP=086aeebc EBP=086aefa8 ESI=da4f4ad8 EDI=00000001 EIP=4005032b 

======== Stack ========
Stack is from 0x86aefa8 to 0x86aeebc

====== Past data ======
Old IP: 0

**Comment by ptitSeb** [comment]
I doubt the issue is in glTexImage2D, this function is commonly used, I would have seen much more repport if it was the case.
To debug Dynarec is a bit complicated. But first, you should try to change `BOX86_DYNAREC_STRONGMEM` and `BOX86_DYNAREC_SAFEFLAGS` value (to 1 or 2) and see if it fixes things. You can use `~/.box86rc` it might be easier.

If nothing works, what I do to debug Dynarec issue is, with a Trace enabled box86:
use `BOX86_DYNAREC_TRACE=2 BOX86_TRACE=0-1 BOX86_TRACE_FILE=$(pwd)/dump-%pid.txt BOX86_LOG=1 BOX86_SHOWSEGV=1 BOX86_LOAD_ADDR=0x20000000 BOX86_DYNAREC_LOG=1 wine XXXX` to launch the program. That will generate a dump of all x86->arm the dynarec generated, and with the LOAD_ADDR, the libs will be loaded at a fixed address, so runs are deterministics.
That I look for SEGFAULT in the traces and look at the dump to see if the generated code around the segfault is correct.
I also use `BOX86_NODYNAREC=0x12345-0x23456` env. v.ar. to disable Dynarec in an interval, to try bisecting an opcode that is incorectly converted (also using `BOX86_LOAD_ADDR=0x20000000` to have deterministic runs).

**Comment by 1322579329** [comment]
Change BOX86_DYNAREC_STRONGMEM and BOX86_DYNAREC_SAFEFLAGS value have same problem, I try to add trace log, dump gpu process log, seems crash in ESI=b0596ad8， then i try to  set BOX86_NODYNAREC=0xb0590ad8-0xb059fad8, glTexImage2D works fine. How to fix it in dynarec?
[dump-11315-1.zip](https://github.com/ptitSeb/box86/files/10335116/dump-11315-1.zip)

**Comment by ptitSeb** [comment]
I don't find that 0xb0590ad8 address in the dump you pasted.

**Comment by 1322579329** [comment]
Sorry, ESI is b0596ad8

**Comment by ptitSeb** [comment]
well, it doesn't mater. NODYNAREC create a zone where the dynarec is not used. You should do a dump without NODYNAREC so the excluded zone appears. That's the only way to fix the dynarec, by looking at what code the dynarec generate to understand what's wrong.

**Comment by ptitSeb** [comment]
Anyway, don't bother, I have identified the issue:
```
0xb05968cb: 65 2B 05 14 00 00 00  SUB Gd, GS:Ed
0xe40d11b8: 18 emited opcodes, inst=4, barrier=0 state=3/1(0), set=3F/0, use=0, need=0/0 sm=1/0, pred=3
Get TLSData
	e59012e4	LDR r1, [r0, #740]
	e590e2c4	LDR LR, [r0, #708]
	e591102c	LDR r1, [r1, #44]
	e15e0001	CMP LR, r1
	0590e2ac	LDREQ LR, [r0, #684]
	0a000008	BEQ +10
	e3001005	MOVW r1, #0x5
	e92d0009	STMFD {r0, r3}
	e580c020	STR r12, [r0, #32]
	e30cee24	MOVW LR, #0xce24
	e346e299	MOVT LR, #0x6299
	e12fff3e	BLX LR
	e1a0e000	MOV LR, r0
	e8bd0009	LDMEA {r0, r3}
	e590c020	LDR r12, [r0, #32]
----TLSData
	e3002014	MOVW r2, #0x14
	e792100e	LDR r1, [r2, LR]
	e0444001	SUB r4, r4, r1
----> potential Son here 0xb05968d2/0xe40d1200
0xb05968d2: FF E6  JMP Ed
0xe40d1200: 9 emited opcodes, inst=5, barrier=3 state=0/0(0), set=0/0, use=0, need=0/0 sm=1/0, pred=4
Jump to next
	e1a0e00a	MOV LR, r10
	e3032da0	MOVW r2, #0x3da0
	e3462333	MOVT r2, #0x6333
	e1a0382e	LSR r3, LR, #0x10
	e7922103	LDR r2, [r2, r3, lsl #2]
	e7ef305e	UBFX r3, LR, #0, #16
	e7923103	LDR r3, [r2, r3, lsl #2]
	e1a0100e	MOV r1, LR
	e12fff13	BX r3
---- END OF BLOCK ---- (6, 1 sons)
```
Here, the SUB opcode should generate defered flags, because the next JUMP goes out of the block. I'll check why it doesn't happens.

**Comment by 1322579329** [comment]
https://github.com/1322579329/box86/commit/34069d48e9b493e82542abaa03aa6e9a9ff6d24e, I add a commit in my fork, If I don't add it, cef crash with Unimplemented Opcode (00) F2 0F 7D C9 0F 29 8C 24, Is it error because  my error commit ?

**Comment by ptitSeb** [comment]
This is wrong. The opcode is HSUBPS, not HADDPS. I'll add the opcode soon.

**Comment by ptitSeb** [comment]
Ok, I pushed some potential fix, can you update box86 and try again?

**Comment by 1322579329** [comment]
Pull the master branch, The Unimplemented Opcode (00) F2 0F 7D ... crash fix， but always have opengl crash 

(nil): Stack is corrupted, aborting

==== CPU Registers ====
EAX=00000000 ECX=00000000 EDX=00000001 EBX=b14e2000 FLAGS=-CPA-S
ESP=0021e5ec EBP=0021e6d8 ESI=b0596ad8 EDI=00000001 EIP=4005032b 

======== Stack ========
Stack is  from 0x21e6d8 to 0x21e5ec
[dump-7380-1.zip](https://github.com/ptitSeb/box86/files/10336433/dump-7380-1.zip)

**Comment by ptitSeb** [comment]
Ok, I pushed another attempt. This should fix it now.

**Comment by 1322579329** [comment]
This commit https://github.com/ptitSeb/box86/commit/2b2478381a72a8e6d95299c9f8291edc706566c3 can fix it.Thanks a lot, ,the cef client load google success.

**Comment by ptitSeb** [comment]
Ok, good :)
This ticket can be closed then?
