### ISSUE TITLE
blank login window for Steam

### ISSUE THREAD

**Issue by weimzh** [ptitSeb/box86#820]
I was following the script here to install steam however I got blank window at login screen:
https://github.com/ptitSeb/box86/blob/master/install_steam.sh

![image](https://user-images.githubusercontent.com/1220443/235677379-1638298d-e24e-44f5-8cab-e74309aa20d7.png)

Machine is: TsingHuaTongFang F860 laptop, Phytium FT2000/4 CPU, AMD Radeon RX 550
Ubuntu 22.04 

![image](https://user-images.githubusercontent.com/1220443/235677835-787a6a8b-e202-419e-99ae-6cce9a184bb7.png)

box86/box64 version:
$ box86 --version
Box86 with Dynarec v0.3.1 1411d44b built on Apr 30 2023 01:09:27
$ box64 --version
Box64 with Dynarec v0.1.3 2976bf5 built on Jul 12 2021 13:53:42

**Comment by ptitSeb** [comment]
I would say you are missing binfmt integration for box64?
The "blank login" happens when `steamwebhelper` fail to start, and it usualy fail to start when box64 is not called automaticaly for it. I don't see any trace of box64 launching, only failled attempt to launch steamwebhelper on that screen shot (or maybe yu have qemu-user or some other x86_64 emulator interfearing?).
(nice machine btw).

Oooh, wait. You version of Box64 is super outdated!!! Update to latest source and Steam will just work.

**Comment by weimzh** [comment]
my bad - upgraade to latest box64 and problem solved.

Thanks
