### ISSUE TITLE
[Question] How the interpreter handle asynchronous signal?

### ISSUE THREAD

**Issue by CosineMath** [ptitSeb/box86#844]
Hello. I am interested in the mechanism of signal emulation of Box86. 

The program may receive asynchronous signals such as SIGINT/SIGUSR1 when running in the interpreter. If it is executing PUSH/POP (those instructions affecting multiple reg/mem), the operation may be interrupted and incomplete (given POP EBX, that means, stack pointer updated but EBX is not updated).

How Box86 solve this problem? Appreciate for any reply.

**Comment by ptitSeb** [comment]
It doesn't.
But most f the time, it doesn't have too.
Because the signal will have the signal handler run, and then, of a signal like SIGUSR1, the original execution is just resumed and the opcode  that was interrupted will just be finished...
If the signal handler change the function flow, it will be using a siglongjump most of time, wich will change all the state, so again, it's not an issue.

For signal like SIGSEGV, were the current execution flow is important, I have made sure that the emory read/write (that can trigger a SEGFAULT), is done in a consistant way so the reading the registers value at the signal make sense.

**Comment by CosineMath** [comment]
Thanks!

So the conclusion is that Box86 **ignore this corner case intentionally**, right? Because most of the time signal handler of SIGINT/SIGUSR1 will just do irrelevant jobs and not try to observe the state of interrupted execution?

**Comment by ptitSeb** [comment]
> Thanks!
> 
> So the conclusion is that Box86 **ignore this corner case intentionally**, right? Because most of the time signal handler of SIGINT/SIGUSR1 will just do irrelevant jobs and not try to observe the state of interrupted execution?

Yes, exactly.

**Comment by CosineMath** [comment]
Thank you!
